name: core
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: 1.4.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_riverpod: 2.3.6
  flutter_screenutil: 5.9.0
  dio: 5.1.1
  http_parser: 4.0.2
  equatable: 2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: 0.4.0
  riverpod_lint: 1.3.2
  freezed: 2.4.1
  build_runner: 2.4.6
  json_serializable: 6.7.1
  flutter_gen_runner: 5.3.1

flutter_gen:
  output: lib/src/generated
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
